-- PRD-01 用户准入与资料认证初始化
-- 小程序用户主表
CREATE TABLE IF NOT EXISTS `app_user` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `openid` VARCHAR(64) DEFAULT NULL COMMENT '小程序openid',
    `unionid` VARCHAR(64) DEFAULT NULL COMMENT '微信unionid',
    `register_source` VARCHAR(32) DEFAULT NULL COMMENT '注册来源',
    `register_time` DATETIME DEFAULT NULL COMMENT '注册时间',
    `last_login_time` DATETIME DEFAULT NULL COMMENT '最近登录时间',
    `account_status` VARCHAR(32) DEFAULT 'ACTIVE' COMMENT '账号状态',
    `first_login_completed` TINYINT DEFAULT 0 COMMENT '是否完成首登资料初始化',

    `avatar` VARCHAR(512) DEFAULT NULL COMMENT '主头像URL',
    `nickname` VARCHAR(64) DEFAULT NULL COMMENT '昵称',
    `gender` VARCHAR(8) DEFAULT NULL COMMENT '性别',
    `birthday` DATE DEFAULT NULL COMMENT '出生日期',
    `age` INT DEFAULT NULL COMMENT '年龄（系统计算）',
    `height` INT DEFAULT NULL COMMENT '身高cm',
    `location_province` VARCHAR(64) DEFAULT NULL COMMENT '居住省',
    `location_city` VARCHAR(64) DEFAULT NULL COMMENT '居住市',
    `location_district` VARCHAR(64) DEFAULT NULL COMMENT '居住区县',
    `hometown_province` VARCHAR(64) DEFAULT NULL COMMENT '家乡省',
    `hometown_city` VARCHAR(64) DEFAULT NULL COMMENT '家乡市',
    `dating_goal` VARCHAR(64) DEFAULT NULL COMMENT '脱单目标',
    `marital_status` VARCHAR(32) DEFAULT NULL COMMENT '婚姻状态',
    `emotional_status` VARCHAR(32) DEFAULT NULL COMMENT '感情状态',
    `school` VARCHAR(128) DEFAULT NULL COMMENT '学校全称',
    `major` VARCHAR(128) DEFAULT NULL COMMENT '专业',
    `education_level` VARCHAR(32) DEFAULT NULL COMMENT '最高学历',

    `about_me` TEXT DEFAULT NULL COMMENT '关于我',
    `hope_they_know` TEXT DEFAULT NULL COMMENT '希望TA了解',
    `voice_intro_url` VARCHAR(512) DEFAULT NULL COMMENT '语音介绍URL',
    `voice_intro_duration` INT DEFAULT NULL COMMENT '语音时长秒',
    `tags` TEXT DEFAULT NULL COMMENT '标签列表JSON',
    `photos` TEXT DEFAULT NULL COMMENT '相册JSON',
    `profile_bg_image` VARCHAR(512) DEFAULT NULL COMMENT '资料页背景图',
    `mbti_type` VARCHAR(16) DEFAULT NULL COMMENT 'MBTI类型',
    `zodiac` VARCHAR(16) DEFAULT NULL COMMENT '星座（系统计算）',
    `profile_score` INT DEFAULT 0 COMMENT '资料完整度分（系统计算）',

    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
    `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
    `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
    `deleted` INT DEFAULT 0 COMMENT '逻辑删除标记',
    PRIMARY KEY (`id`),
    INDEX `idx_openid` (`openid`),
    INDEX `idx_account_status` (`account_status`),
    INDEX `idx_nickname` (`nickname`),
    INDEX `idx_school` (`school`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='小程序用户主表';

-- 用户认证与审核状态表
CREATE TABLE IF NOT EXISTS `app_user_verification` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `user_id` BIGINT NOT NULL COMMENT '用户ID',
    `real_name_status` VARCHAR(32) DEFAULT 'NOT_SUBMITTED' COMMENT '实名认证状态',
    `real_name` VARCHAR(128) DEFAULT NULL COMMENT '真实姓名（加密存储）',
    `id_card` VARCHAR(128) DEFAULT NULL COMMENT '身份证号（加密存储）',
    `real_name_submit_time` DATETIME DEFAULT NULL COMMENT '实名认证提交时间',
    `real_name_result_time` DATETIME DEFAULT NULL COMMENT '实名认证结果时间',
    `real_name_reject_reason` VARCHAR(512) DEFAULT NULL COMMENT '实名驳回原因',
    `education_status` VARCHAR(32) DEFAULT 'NOT_SUBMITTED' COMMENT '学历认证状态',
    `education_method` VARCHAR(32) DEFAULT NULL COMMENT '认证方式',
    `education_submit_time` DATETIME DEFAULT NULL COMMENT '学历认证提交时间',
    `education_result_time` DATETIME DEFAULT NULL COMMENT '学历认证结果时间',
    `education_reject_reason` VARCHAR(512) DEFAULT NULL COMMENT '学历驳回原因',
    `avatar_verify_status` VARCHAR(32) DEFAULT 'NOT_SUBMITTED' COMMENT '头像认证状态',
    `avatar_verify_submit_time` DATETIME DEFAULT NULL COMMENT '头像认证提交时间',
    `avatar_verify_result_time` DATETIME DEFAULT NULL COMMENT '头像认证结果时间',
    `avatar_verify_reject_reason` VARCHAR(512) DEFAULT NULL COMMENT '头像驳回原因',
    `profile_photo_audit_status` VARCHAR(32) DEFAULT 'NOT_SUBMITTED' COMMENT '资料照片审核状态',
    `profile_photo_submit_time` DATETIME DEFAULT NULL COMMENT '照片审核提交时间',
    `profile_photo_reject_reason` VARCHAR(512) DEFAULT NULL COMMENT '照片驳回原因',
    `open_text_audit_status` VARCHAR(32) DEFAULT 'NOT_SUBMITTED' COMMENT '文字审核状态',
    `open_text_submit_time` DATETIME DEFAULT NULL COMMENT '文字审核提交时间',
    `open_text_reject_reason` VARCHAR(512) DEFAULT NULL COMMENT '文字驳回原因',
    `verify_level` INT DEFAULT 0 COMMENT '已完成认证数量',
    `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
    `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
    `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
    `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
    `deleted` INT DEFAULT 0 COMMENT '逻辑删除标记',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_user_id` (`user_id`),
    INDEX `idx_real_name_status` (`real_name_status`),
    INDEX `idx_education_status` (`education_status`),
    INDEX `idx_avatar_verify_status` (`avatar_verify_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户认证与审核状态表';
