/** 由 scripts/upload-miniapp-oss-icons.mjs 生成；禁止手写密钥或本地回退路径。 */
export const miniappOssIcons = Object.freeze({
  coinGold: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/c29d6952d277b580/coin-gold.png',
  coinUsageWhisper: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/2ae61de168714990/whisper.png',
  coinUsageHeartbeat: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/95503a52fa573620/heartbeat.png',
  coinUsageIdealUnlock: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/d0a25f0413bb55e3/ideal-unlock.png',
  coinUsageBoost: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/da18ab0e92a514c7/boost.png',
  coinUsageCuratedUnlock: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/80e8c7a908cd3fc6/curated-unlock.png',
  coinUsageRecommend: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/eca07077a103124a/recommend.png',
  coinUsageAnonymousUnlock: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/d7ba5c587ae5d330/anonymous-unlock.png',
  coinUsageLimitedActivity: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/934d99749921ab80/limited-activity.png',
  memberDividerLeft: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/c32873f2d5bbb029/member-slice-group-5-a.png',
  memberDividerRight: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/947063ce7ca559c0/member-slice-group-5-b.png',
  memberBenefitMatch: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/bb0db47013381ae6/member-slice-match.png',
  memberBenefitEyeOpen: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/d824d6dd6bda86ab/member-slice-eye-open.png',
  memberBenefitGreeting: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/53c1e311f480a67c/member-slice-greeting-a.png',
  memberBenefitRecommend: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/fa562f4c8017b839/member-slice-recommend.png',
  memberBenefitFilter: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/1b1e3c374cb79ffe/member-slice-filter.png',
  memberBenefitExposure: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/8d1d9fe1c8dc4107/member-slice-exposure.png',
  memberBenefitStealth: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/1b0f82bf277d1e54/member-slice-stealth.png',
  memberBenefitReplay: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/9e38d370761e9630/member-slice-greeting-b.png',
  memberBenefitDailyHeart: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/a8924076b9c96dbd/member-slice-my-2.png',
  loginMethodWechat: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/a41e7b9dc62e3815/login-method-wechat.png',
  loginMethodPhone: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/571ffa17f16884a1/login-method-phone.png',
  genderFemale: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/64f6756070a9536d/gender-female.webp',
  genderMale: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/e6487f6f994c4bfa/gender-male.webp',
  verificationCertAvatar: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/680e99e6dde9c976/cert-avatar.webp',
  verificationCertRealName: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/5c6ee64e62002345/cert-realname.webp',
  verificationCertEducation: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/ddbb8cb619a8f586/cert-education.webp',
  verificationUploadCamera: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/914b3b279600d7ce/upload-camera.webp',
  profilePost: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/cf6df36ac1818aa0/icon-post.png',
  profileService: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/7fe214ee94d6edf9/icon-service.png',
  profileSettings: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/cb15fc215e87e972/icon-settings.png',
  profileCertification: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/9c33a27875169664/icon-cert.png',
  profileBoostButton: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/10654d7bbfcc207b/boost-button.png',
  profileVipBanner: 'https://shikongxiehou.oss-cn-shanghai.aliyuncs.com/miniapp/ui-icons/03c32b0a289c32d3/vip-banner.webp',
} as const)

export type MiniappOssIconKey = keyof typeof miniappOssIcons
