import type { RouterVO } from '@/api/menu';

export const adminFallbackMenuTree: RouterVO[] = [
  {
    id: 1,
    parentId: 0,
    name: 'Workbench',
    path: '/dashboard',
    component: 'dashboard/DashboardPage',
    meta: { title: '工作台', icon: 'LayoutDashboard' },
    sort: 1,
    children: [
      {
        id: 11,
        parentId: 1,
        name: 'Dashboard',
        path: '/dashboard',
        component: 'dashboard/DashboardPage',
        meta: { title: '首页概览', icon: 'LayoutDashboard' },
        sort: 1,
        children: [],
      },
    ],
  },
  {
    id: 2,
    parentId: 0,
    name: 'CustomerCenter',
    path: '/customers',
    component: 'Layout',
    meta: { title: '用户管理中心', icon: 'Users' },
    sort: 2,
    children: [
      {
        id: 21,
        parentId: 2,
        name: 'Customers',
        path: '/customers',
        component: 'customers/CustomersPage',
        meta: { title: '客户列表', icon: 'Users' },
        sort: 1,
        children: [],
      },
      {
        id: 22,
        parentId: 2,
        name: 'Users',
        path: '/users',
        component: 'placeholder/PlaceholderPage',
        meta: { title: '用户管理', icon: 'UserCheck' },
        sort: 2,
        children: [],
      },
      {
        id: 23,
        parentId: 2,
        name: 'Match',
        path: '/match',
        component: 'placeholder/PlaceholderPage',
        meta: { title: '匹配', icon: 'Heart' },
        sort: 3,
        children: [],
      },
      {
        id: 24,
        parentId: 2,
        name: 'Scale',
        path: '/scale',
        component: 'placeholder/PlaceholderPage',
        meta: { title: '量表', icon: 'ClipboardList' },
        sort: 4,
        children: [],
      },
      {
        id: 25,
        parentId: 2,
        name: 'Matchmaking',
        path: '/matchmaking',
        component: 'placeholder/PlaceholderPage',
        meta: { title: '牵线台操作', icon: 'GitBranch' },
        sort: 5,
        children: [],
      },
      {
        id: 26,
        parentId: 2,
        name: 'Tags',
        path: '/tags',
        component: 'placeholder/PlaceholderPage',
        meta: { title: '画像标签', icon: 'Tags' },
        sort: 6,
        children: [],
      },
      {
        id: 27,
        parentId: 2,
        name: 'MatchRules',
        path: '/match-rules',
        component: 'placeholder/PlaceholderPage',
        meta: { title: '匹配规则', icon: 'Settings' },
        sort: 7,
        children: [],
      },
    ],
  },
  {
    id: 3,
    parentId: 0,
    name: 'Business',
    path: '/coins',
    component: 'Layout',
    meta: { title: '商业化与运营', icon: 'Briefcase' },
    sort: 3,
    children: [
      {
        id: 31,
        parentId: 3,
        name: 'Coins',
        path: '/coins',
        component: 'placeholder/PlaceholderPage',
        meta: { title: '千寻币', icon: 'Coins' },
        sort: 1,
        children: [],
      },
      {
        id: 32,
        parentId: 3,
        name: 'Checkin',
        path: '/checkin',
        component: 'placeholder/PlaceholderPage',
        meta: { title: '签到', icon: 'CalendarCheck' },
        sort: 2,
        children: [],
      },
      {
        id: 33,
        parentId: 3,
        name: 'Products',
        path: '/products',
        component: 'placeholder/PlaceholderPage',
        meta: { title: '商品', icon: 'ShoppingBag' },
        sort: 3,
        children: [],
      },
      {
        id: 34,
        parentId: 3,
        name: 'Operations',
        path: '/operations',
        component: 'placeholder/PlaceholderPage',
        meta: { title: '运营', icon: 'TrendingUp' },
        sort: 4,
        children: [],
      },
      {
        id: 35,
        parentId: 3,
        name: 'Finance',
        path: '/finance',
        component: 'placeholder/PlaceholderPage',
        meta: { title: '财务', icon: 'DollarSign' },
        sort: 5,
        children: [],
      },
      {
        id: 36,
        parentId: 3,
        name: 'Data',
        path: '/data',
        component: 'placeholder/PlaceholderPage',
        meta: { title: '数据', icon: 'BarChart3' },
        sort: 6,
        children: [],
      },
      {
        id: 37,
        parentId: 3,
        name: 'Content',
        path: '/content',
        component: 'placeholder/PlaceholderPage',
        meta: { title: '内容', icon: 'FileText' },
        sort: 7,
        children: [],
      },
    ],
  },
  {
    id: 4,
    parentId: 0,
    name: 'System',
    path: '/system/user',
    component: 'Layout',
    meta: { title: '系统管理', icon: 'Shield' },
    sort: 4,
    children: [
      {
        id: 41,
        parentId: 4,
        name: 'UserManagement',
        path: '/system/user',
        component: 'system/UserManagement',
        meta: { title: '用户管理', icon: 'Users' },
        sort: 1,
        children: [],
      },
      {
        id: 42,
        parentId: 4,
        name: 'RoleManagement',
        path: '/system/role',
        component: 'system/RoleManagement',
        meta: { title: '角色管理', icon: 'Lock' },
        sort: 2,
        children: [],
      },
      {
        id: 43,
        parentId: 4,
        name: 'MenuManagement',
        path: '/system/menu',
        component: 'system/MenuManagement',
        meta: { title: '菜单管理', icon: 'Menu' },
        sort: 3,
        children: [],
      },
    ],
  },
  {
    id: 5,
    parentId: 0,
    name: 'Support',
    path: '/support',
    component: 'Layout',
    meta: { title: '客服中心', icon: 'HeadphonesIcon' },
    sort: 5,
    children: [
      {
        id: 51,
        parentId: 5,
        name: 'Support',
        path: '/support',
        component: 'placeholder/PlaceholderPage',
        meta: { title: '客服', icon: 'HeadphonesIcon' },
        sort: 1,
        children: [],
      },
    ],
  },
];

export function getAdminMenuTree(menuTree: RouterVO[]) {
  return menuTree.length > 0 ? menuTree : adminFallbackMenuTree;
}

export function sortMenuItems(items: RouterVO[]) {
  return [...items].sort((a, b) => (a.sort ?? 0) - (b.sort ?? 0));
}

