export const demoData = {
  adminUsers: [
    {
      id: 'U10001',
      name: '林知夏',
      gender: '女',
      age: 29,
      identity: '职场人',
      city: '上海 浦东',
      phone: '138****9001',
      profileScore: 76,
      accountStatus: 'NORMAL',
      accessStatus: 'BLOCKED_CERTIFICATION',
      avatarStatus: 'REVIEWING',
      realNameStatus: 'NOT_SUBMITTED',
      educationStatus: 'NOT_SUBMITTED',
      missingItems: ['REAL_NAME', 'EDUCATION', 'PROFILE_BACKGROUND'],
      remark: '希望匹配成熟稳定、上海或杭州工作的人。近期工作较忙，适合周末跟进。',
    },
    {
      id: 'U10002',
      name: '陈屿',
      gender: '男',
      age: 31,
      identity: '职场人',
      city: '杭州 西湖',
      phone: '159****2308',
      profileScore: 92,
      accountStatus: 'NORMAL',
      accessStatus: 'FULL_ACCESS',
      avatarStatus: 'APPROVED',
      realNameStatus: 'APPROVED',
      educationStatus: 'APPROVED',
      missingItems: [],
      remark: '三重认证完成，可进入核心推荐池。偏好杭州同城或一年内可规划同城。',
    },
    {
      id: 'U10003',
      name: '许安然',
      gender: '女',
      age: 23,
      identity: '在校生',
      city: '南京 鼓楼',
      phone: '186****7710',
      profileScore: 63,
      accountStatus: 'FROZEN',
      accessStatus: 'BLOCKED_CERTIFICATION',
      avatarStatus: 'REJECTED',
      realNameStatus: 'REVIEWING',
      educationStatus: 'REVIEWING',
      missingItems: ['AVATAR', 'EXTENDED_PROFILE'],
      remark: '头像因模糊驳回，需重新上传清晰正脸照。实名与学历已进入审核队列。',
    },
  ],
  audits: {
    avatar: [
      { id: 'A-1001', userId: 'U10001', userName: '林知夏', target: '主头像', status: 'PENDING_MANUAL', source: 'MANUAL', submittedAt: '2026-06-27 09:24', reason: '' },
      { id: 'A-1002', userId: 'U10003', userName: '许安然', target: '主头像', status: 'REJECTED', source: 'MACHINE', submittedAt: '2026-06-26 18:12', reason: '图片过度模糊' },
    ],
    realName: [
      { id: 'R-2001', userId: 'U10003', userName: '许安然', target: '姓名/身份证/手机号', status: 'PENDING_REVIEW', source: 'MACHINE', submittedAt: '2026-06-27 10:05', reason: '' },
      { id: 'R-2002', userId: 'U10001', userName: '林知夏', target: '真实姓名 + 身份证号', status: 'NOT_SUBMITTED', source: 'USER', submittedAt: '', reason: '轻量引导后未进入实名' },
    ],
    education: [
      { id: 'E-3001', userId: 'U10003', userName: '许安然', target: '在校生学生证 2/4', status: 'PENDING_MANUAL', source: 'MANUAL', submittedAt: '2026-06-27 08:20', reason: '' },
      { id: 'E-3002', userId: 'U10002', userName: '陈屿', target: '学信网在线验证码', status: 'APPROVED', source: 'MACHINE', submittedAt: '2026-06-26 11:45', reason: '' },
    ],
    profilePhoto: [
      { id: 'P-4001', userId: 'U10001', userName: '林知夏', target: '资料背景图', status: 'PENDING_MANUAL', source: 'MACHINE', submittedAt: '2026-06-27 12:10', reason: '' },
      { id: 'P-4002', userId: 'U10003', userName: '许安然', target: '相册照片', status: 'REJECTED', source: 'MANUAL', submittedAt: '2026-06-26 20:42', reason: '含联系方式' },
    ],
    openText: [
      { id: 'T-5001', userId: 'U10001', userName: '林知夏', target: '自我介绍', status: 'PENDING_MANUAL', source: 'MACHINE', submittedAt: '2026-06-27 11:31', reason: '' },
      { id: 'T-5002', userId: 'U10002', userName: '陈屿', target: '资料问答', status: 'APPROVED', source: 'MANUAL', submittedAt: '2026-06-26 15:19', reason: '' },
    ],
  },
  accessConfig: {
    ageRange: { min: 18, max: 60 },
    coreRules: ['REAL_NAME_APPROVED', 'AVATAR_APPROVED', 'EDUCATION_APPROVED', 'ACCOUNT_NORMAL'],
    profileScore: { student: 100, worker: 96 },
    sms: { countdownSeconds: 60, validMinutes: 5, dailyLimit: 10 },
    auditSlaHours: { avatar: 12, realName: 24, education: 24 },
  },
  miniappProfile: {
    userId: 'U10001',
    nickname: '知夏',
    phoneMasked: '138****9001',
    gender: 'FEMALE',
    birthday: '1996-08-18',
    identity: 'WORKER',
    educationLevel: 'BACHELOR',
    location: '上海市 浦东新区',
    profileScore: 76,
    accessStatus: 'BLOCKED_CERTIFICATION',
    accessStatusLabel: '认证未完成',
    missingItems: ['REAL_NAME', 'EDUCATION'],
  },
  verificationStatus: {
    avatar: 'REVIEWING',
    realName: 'NOT_SUBMITTED',
    education: 'NOT_SUBMITTED',
    coreAccess: 'BLOCKED',
    blockers: ['REAL_NAME', 'EDUCATION'],
  },
};
