import { useEffect, useMemo, useState } from 'react';
import { History, ShieldAlert } from 'lucide-react';
import { getMessageConfig, getMessageConfigLogs, publishMessageConfig, updateGlobalSend, type ConfigLog, type MessageConfig } from '@/api/message';
import { Button } from '@/components/ui/button';
import { Dialog, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Drawer } from '@/components/ui/drawer';
import { showToast } from '@/components/ui/toast';
import { usePermission } from '@/hooks/usePermission';
import { CommunityPage, CommunityPageHeader, DetailSection, Field, Input, PermissionState, StatGrid, normalizePage, unwrapData } from '@/features/community/communityUi';

type Draft = Pick<MessageConfig,'femaleProtectionEnabled'|'femaleProtectionDays'|'whisperExpireDays'|'whisperCooldownDays'>;
const draftOf=(v:MessageConfig):Draft=>({femaleProtectionEnabled:v.femaleProtectionEnabled,femaleProtectionDays:v.femaleProtectionDays,whisperExpireDays:v.whisperExpireDays,whisperCooldownDays:v.whisperCooldownDays});
const same=(a:Draft|null,b:Draft|null)=>JSON.stringify(a)===JSON.stringify(b);

export default function MessageConfigPage(){
  const {hasAnyPermission}=usePermission(); const canView=hasAnyPermission('message:config:view'); const canEdit=hasAnyPermission('message:config:edit');
  const [config,setConfig]=useState<MessageConfig|null>(null); const [draft,setDraft]=useState<Draft|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const [saveOpen,setSaveOpen]=useState(false); const [switchOpen,setSwitchOpen]=useState(false); const [remark,setRemark]=useState(''); const [saving,setSaving]=useState(false);
  const [logsOpen,setLogsOpen]=useState(false); const [logs,setLogs]=useState<ConfigLog[]>([]); const [logsLoading,setLogsLoading]=useState(false);
  async function load(){setLoading(true);setError('');try{const value=unwrapData<MessageConfig>(await getMessageConfig(),null as any);setConfig(value);setDraft(draftOf(value));}catch(e:any){setError(e?.message||'配置加载失败');}finally{setLoading(false);}}
  useEffect(()=>{if(canView)void load();else setLoading(false);},[canView]);
  const dirty=useMemo(()=>!same(config?draftOf(config):null,draft),[config,draft]);
  const cards=config?[{code:'global',label:'全局发送',value:config.globalSend?.enabled?'开启':'关闭'},{code:'female',label:'女性保护',value:config.femaleProtectionEnabled?'开启':'关闭'},{code:'days',label:'保护期',value:`${config.femaleProtectionDays} 天`},{code:'cooldown',label:'到期后冷却',value:`${config.whisperCooldownDays} 天`},{code:'expire',label:'待回应有效期',value:`${config.whisperExpireDays} 天`}]:[];
  const valid=()=>draft&&[draft.femaleProtectionDays,draft.whisperExpireDays,draft.whisperCooldownDays].every(v=>Number.isInteger(Number(v))&&Number(v)>=1&&Number(v)<=30);
  async function save(){if(!config||!draft||remark.trim().length<5)return showToast('变更原因至少填写5个字符','error');if(!valid())return showToast('天数必须是1至30的整数','error');setSaving(true);try{const value=unwrapData<MessageConfig>(await publishMessageConfig({...draft,expectedVersion:config.versionNo,remark:remark.trim(),ordinaryMessageRetainDays:config.ordinaryMessageRetainDays,systemMessageVisibleDays:config.systemMessageVisibleDays,reportEvidenceRetainDays:config.reportEvidenceRetainDays,severeEvidenceRetainDays:config.severeEvidenceRetainDays,sensitiveAuditRetainDays:config.sensitiveAuditRetainDays}),null as any);setConfig(value);setDraft(draftOf(value));setSaveOpen(false);setRemark('');showToast('配置新版本已发布','success');}catch(e:any){if(/版本|30020/.test(e?.message||''))void load();}finally{setSaving(false);}}
  async function toggle(){if(!config?.globalSend||remark.trim().length<5)return showToast('变更原因至少填写5个字符','error');setSaving(true);try{const runtime=unwrapData<any>(await updateGlobalSend({enabled:!config.globalSend.enabled,expectedVersion:config.globalSend.version,reason:remark.trim()}),null);setConfig({...config,globalSend:runtime});setSwitchOpen(false);setRemark('');showToast(runtime.enabled?'全局发送已开启':'全局发送已关闭','success');}finally{setSaving(false);}}
  async function openLogs(){setLogsOpen(true);setLogsLoading(true);try{setLogs(normalizePage<ConfigLog>(await getMessageConfigLogs({page:1,size:20})).records);}finally{setLogsLoading(false);}}
  if(!canView)return <CommunityPage><CommunityPageHeader title="社交权限与消息配置" description="配置新互动安全规则。"/><PermissionState copy="无权限查看消息配置"/></CommunityPage>;
  if(loading)return <CommunityPage><p className="py-24 text-center text-slate-500">配置加载中...</p></CommunityPage>;
  if(error||!config||!draft)return <CommunityPage><div className="py-24 text-center"><p className="text-rose-600">{error||'配置不存在'}</p><Button className="mt-4" variant="outline" onClick={()=>void load()}>重试</Button></div></CommunityPage>;
  const numberField=(key:'femaleProtectionDays'|'whisperExpireDays'|'whisperCooldownDays',label:string,tip:string)=><Field label={label}><Input type="number" min={1} max={30} disabled={!canEdit||(key==='femaleProtectionDays'&&!draft.femaleProtectionEnabled)} value={draft[key]} onChange={e=>setDraft({...draft,[key]:Number(e.target.value)})}/><span className="block text-xs font-normal text-slate-500">{tip}</span></Field>;
  return <CommunityPage>
    <CommunityPageHeader title="社交权限与消息配置" description="普通规则按版本发布并只影响新对象；全局发送安全开关立即影响新发送。" actions={<><Button variant="outline" onClick={()=>void openLogs()}><History className="mr-1.5 h-4 w-4"/>查看变更日志</Button>{canEdit&&<Button disabled={!dirty} onClick={()=>{setRemark('');setSaveOpen(true);}}>保存当前配置</Button>}</>}/>
    <StatGrid cards={cards}/>
    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
      <section className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between"><strong>全局发送安全开关</strong><span className={`rounded-full px-2.5 py-1 text-xs ${config.globalSend.enabled?'bg-emerald-100 text-emerald-700':'bg-rose-100 text-rose-700'}`}>{config.globalSend.enabled?'开启':'关闭'}</span></div><p className="mt-3 text-sm leading-6 text-slate-600">关闭后所有新私信和悄悄话立即禁发，历史对象状态不改写。</p>{canEdit&&<Button className="mt-4 w-full" variant={config.globalSend.enabled?'destructive':'default'} onClick={()=>{setRemark('');setSwitchOpen(true);}}>切换开关</Button>}</section>
      <section className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between"><strong>女性保护机制</strong><button type="button" disabled={!canEdit} onClick={()=>setDraft({...draft,femaleProtectionEnabled:!draft.femaleProtectionEnabled})} className={`rounded-full px-3 py-1 text-xs ${draft.femaleProtectionEnabled?'bg-emerald-100 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{draft.femaleProtectionEnabled?'开启':'关闭'}</button></div><p className="mt-3 text-sm leading-6 text-slate-600">匹配成功后按保护期限制男方先发，仅影响新建会话。</p></section>
      <section className="rounded-xl border border-slate-200 p-4">{numberField('femaleProtectionDays','女性保护期天数','保存到新版本，只影响新建会话。')}</section>
      <section className="rounded-xl border border-slate-200 p-4">{numberField('whisperExpireDays','悄悄话有效期','只影响新申请并写入有效期快照。')}</section>
      <section className="rounded-xl border border-slate-200 p-4">{numberField('whisperCooldownDays','到期后冷却期','只影响新申请并写入冷却期快照。')}</section>
      <section className="rounded-xl border border-slate-200 p-4"><strong>普通私信开放条件</strong><p className="mt-3 text-sm leading-6 text-slate-600">固定为“匹配成功后开放”，不可配置为互关或任意人私信。</p></section>
      <section className="rounded-xl border border-slate-200 p-4"><strong>分类留存基线</strong><p className="mt-3 text-sm leading-6 text-slate-600">普通消息 {config.ordinaryMessageRetainDays} 天；系统消息 {config.systemMessageVisibleDays} 天；举报证据 {config.reportEvidenceRetainDays} 天；严重证据 {config.severeEvidenceRetainDays} 天；审计 {config.sensitiveAuditRetainDays} 天。</p></section>
      <section className="rounded-xl border border-slate-200 p-4"><strong>官方助手内容范围</strong><p className="mt-3 text-sm leading-6 text-slate-600">仅允许首次介绍、安全提示、帮助入口和服务号/公众号关注引导。</p></section>
      <section className="rounded-xl border border-slate-200 p-4"><strong>系统消息模板范围</strong><p className="mt-3 text-sm leading-6 text-slate-600">治理、资产、邀请、社区运营、平台与安全类模板；模板编辑由文案与消息中心承接。</p></section>
    </div>
    <Dialog open={saveOpen} onClose={()=>setSaveOpen(false)} layer="confirmation"><DialogHeader><DialogTitle>保存配置确认</DialogTitle></DialogHeader><div className="mt-4 space-y-4"><p className="text-sm text-slate-600">将发布新配置版本，仅影响新会话和新申请，不回算历史对象。</p><Input maxLength={100} value={remark} onChange={e=>setRemark(e.target.value)} placeholder="填写5-100字变更原因"/><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setSaveOpen(false)}>取消</Button><Button disabled={saving} onClick={()=>void save()}>{saving?'保存中...':'确认保存'}</Button></div></div></Dialog>
    <Dialog open={switchOpen} onClose={()=>setSwitchOpen(false)} layer="confirmation"><DialogHeader><DialogTitle>切换全局发送安全开关</DialogTitle></DialogHeader><div className="mt-4 space-y-4"><div className="flex gap-2 rounded-lg bg-amber-50 p-3 text-sm text-amber-700"><ShieldAlert className="h-5 w-5 shrink-0"/>切换后立即{config.globalSend.enabled?'阻断':'恢复'}新私信和悄悄话发送，不改写历史对象。</div><Input maxLength={100} value={remark} onChange={e=>setRemark(e.target.value)} placeholder="填写5-100字变更原因"/><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setSwitchOpen(false)}>取消</Button><Button variant={config.globalSend.enabled?'destructive':'default'} disabled={saving} onClick={()=>void toggle()}>确认切换</Button></div></div></Dialog>
    <Drawer open={logsOpen} onClose={()=>setLogsOpen(false)} title="消息配置变更日志" description="按时间倒序展示规则发布与安全开关变更。">{logsLoading?<p>加载中...</p>:!logs.length?<p className="text-slate-400">暂无变更日志</p>:<div className="space-y-3">{logs.map(log=><DetailSection key={log.id} title={`${log.operatorName||'-'} · ${log.action}`}><p>{log.remark||'-'}</p><p className="mt-2 text-xs text-slate-400">{log.createTime||'-'}</p><details className="mt-2"><summary className="cursor-pointer text-xs text-blue-600">查看变更摘要</summary><pre className="mt-2 overflow-auto rounded bg-slate-50 p-2 text-xs">{log.beforeValue||'-'}{`\n→\n`}{log.afterValue||'-'}</pre></details></DetailSection>)}</div>}</Drawer>
  </CommunityPage>;
}
