spring:
  datasource:
    url: jdbc:mysql://${DEV_DB_HOST:rm-bp11i1ru1405fb2iqio.mysql.rds.aliyuncs.com}:${DEV_DB_PORT:3306}/${DEV_DB_NAME:shikongxiehou}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${DEV_DB_USER:}
    password: ${DEV_DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${DEV_REDIS_HOST:r-bp182i9r17g2ybq30gpd.redis.rds.aliyuncs.com}
      port: ${DEV_REDIS_PORT:6379}
      username: ${DEV_REDIS_USERNAME:}
      database: ${DEV_REDIS_DATABASE:1}
      password: ${DEV_REDIS_PASSWORD:}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  enable: true

logging:
  level:
    com.spacetime: DEBUG

oss:
  endpoint: ${DEV_OSS_ENDPOINT:https://oss-cn-shanghai.aliyuncs.com}
  access-key-id: ${DEV_OSS_ACCESS_KEY_ID:}
  access-key-secret: ${DEV_OSS_ACCESS_KEY_SECRET:}
  bucket-name: ${DEV_OSS_BUCKET_NAME:spacetime}
