-- ======================================================
-- 小程序用户与认证基础表安全迁移
-- ======================================================

CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    openid VARCHAR(128) DEFAULT NULL COMMENT '小程序 openid',
    unionid VARCHAR(128) DEFAULT NULL COMMENT '微信 unionid',
    phone VARCHAR(30) DEFAULT NULL COMMENT '微信授权手机号',
    phone_hash VARCHAR(64) DEFAULT NULL COMMENT '手机号 SHA-256 哈希',
    register_source VARCHAR(30) DEFAULT 'WECHAT' COMMENT '注册来源',
    register_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
    last_login_time DATETIME DEFAULT NULL COMMENT '最近登录时间',
    account_status VARCHAR(20) DEFAULT 'NORMAL' COMMENT '账号状态',
    first_login_completed TINYINT DEFAULT 0 COMMENT '是否完成首登资料初始化',
    avatar VARCHAR(500) DEFAULT NULL COMMENT '主头像 URL',
    nickname VARCHAR(50) DEFAULT NULL COMMENT '昵称',
    gender VARCHAR(10) DEFAULT NULL COMMENT '性别',
    birthday DATE DEFAULT NULL COMMENT '出生日期',
    age INT DEFAULT NULL COMMENT '年龄',
    height INT DEFAULT NULL COMMENT '身高 cm',
    location_province VARCHAR(50) DEFAULT NULL COMMENT '居住省',
    location_city VARCHAR(50) DEFAULT NULL COMMENT '居住市',
    location_district VARCHAR(50) DEFAULT NULL COMMENT '居住区县',
    hometown_province VARCHAR(50) DEFAULT NULL COMMENT '家乡省',
    hometown_city VARCHAR(50) DEFAULT NULL COMMENT '家乡市',
    dating_goal VARCHAR(30) DEFAULT NULL COMMENT '脱单目标',
    marital_status VARCHAR(30) DEFAULT NULL COMMENT '婚姻状态',
    emotional_status VARCHAR(30) DEFAULT NULL COMMENT '感情状态',
    school VARCHAR(100) DEFAULT NULL COMMENT '学校全称',
    major VARCHAR(100) DEFAULT NULL COMMENT '专业',
    education_level VARCHAR(30) DEFAULT NULL COMMENT '最高学历',
    about_me VARCHAR(500) DEFAULT NULL COMMENT '关于我',
    voice_intro_url VARCHAR(500) DEFAULT NULL COMMENT '语音介绍 URL',
    voice_intro_duration INT DEFAULT NULL COMMENT '语音时长秒',
    tags JSON DEFAULT NULL COMMENT '标签列表 JSON',
    photos JSON DEFAULT NULL COMMENT '相册 JSON',
    profile_bg_image VARCHAR(500) DEFAULT NULL COMMENT '资料页背景图',
    mbti_type VARCHAR(10) DEFAULT NULL COMMENT 'MBTI 类型',
    zodiac VARCHAR(10) DEFAULT NULL COMMENT '星座',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT DEFAULT NULL,
    updated_by BIGINT DEFAULT NULL,
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除：0=正常，1=已删除',
    UNIQUE KEY uk_app_user_openid (openid),
    UNIQUE KEY uk_app_user_phone_hash_deleted (phone_hash, deleted),
    INDEX idx_app_user_account_status (account_status),
    INDEX idx_app_user_first_login (first_login_completed),
    INDEX idx_app_user_gender (gender),
    INDEX idx_app_user_school (school),
    INDEX idx_app_user_register_time (register_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='小程序用户主表';

CREATE TABLE IF NOT EXISTS app_user_verification (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL COMMENT '用户 ID',
    real_name_status VARCHAR(20) DEFAULT 'NOT_CERTIFIED' COMMENT '实名认证状态',
    real_name VARCHAR(50) DEFAULT NULL COMMENT '真实姓名',
    id_card VARCHAR(20) DEFAULT NULL COMMENT '身份证号',
    real_name_submit_time DATETIME DEFAULT NULL COMMENT '实名认证提交时间',
    real_name_result_time DATETIME DEFAULT NULL COMMENT '实名认证结果时间',
    real_name_reject_reason VARCHAR(200) DEFAULT NULL COMMENT '实名驳回原因',
    education_status VARCHAR(20) DEFAULT 'NOT_CERTIFIED' COMMENT '学历认证状态',
    education_method VARCHAR(30) DEFAULT NULL COMMENT '认证方式',
    education_submit_time DATETIME DEFAULT NULL COMMENT '学历认证提交时间',
    education_result_time DATETIME DEFAULT NULL COMMENT '学历认证结果时间',
    education_reject_reason VARCHAR(200) DEFAULT NULL COMMENT '学历驳回原因',
    avatar_verify_status VARCHAR(20) DEFAULT 'NOT_CERTIFIED' COMMENT '头像认证状态',
    avatar_verify_submit_time DATETIME DEFAULT NULL COMMENT '头像认证提交时间',
    avatar_verify_result_time DATETIME DEFAULT NULL COMMENT '头像认证结果时间',
    avatar_verify_reject_reason VARCHAR(200) DEFAULT NULL COMMENT '头像驳回原因',
    profile_photo_audit_status VARCHAR(20) DEFAULT 'NOT_SUBMITTED' COMMENT '资料照片审核状态',
    profile_photo_submit_time DATETIME DEFAULT NULL COMMENT '照片审核提交时间',
    profile_photo_reject_reason VARCHAR(200) DEFAULT NULL COMMENT '照片驳回原因',
    open_text_audit_status VARCHAR(20) DEFAULT 'NOT_SUBMITTED' COMMENT '文字审核状态',
    open_text_submit_time DATETIME DEFAULT NULL COMMENT '文字审核提交时间',
    open_text_reject_reason VARCHAR(200) DEFAULT NULL COMMENT '文字驳回原因',
    verify_level INT DEFAULT 0 COMMENT '已完成认证数量',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT DEFAULT NULL,
    updated_by BIGINT DEFAULT NULL,
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除：0=正常，1=已删除',
    UNIQUE KEY uk_app_user_verification_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户认证与审核状态表';
