-- ======================================================
-- PRD-01 用户准入与资料认证初始化：统一审核记录表
-- 说明：
-- 1. 本脚本只新增统一审核记录与审核历史，不删除旧分表。
-- 2. 旧表下线/删除必须在数据迁移和用户确认后单独执行。
-- ======================================================

CREATE TABLE IF NOT EXISTS app_user_audit_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '自增主键',
    user_id BIGINT NOT NULL COMMENT '用户 ID',
    audit_group VARCHAR(30) NOT NULL COMMENT '审核分组：CERTIFICATION认证/MEDIA媒体图片/TEXT开放文字/VOICE语音介绍',
    audit_type VARCHAR(50) NOT NULL COMMENT '审核类型：REAL_NAME/AVATAR/EDUCATION/ALBUM_PHOTO/PROFILE_BG/ABOUT_ME/HOPE_THEY_KNOW/PROFILE_QA/VOICE_INTRO',
    object_id BIGINT DEFAULT NULL COMMENT '被审核对象 ID，如相册单张、背景图、问答项',
    object_key VARCHAR(80) DEFAULT NULL COMMENT '被审核对象业务 key，如相册槽位、文本字段、问答 key',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '审核状态：PENDING待审核/REVIEWING审核中/APPROVED已通过/REJECTED已驳回/EXPIRED已失效',
    audit_source VARCHAR(20) NOT NULL DEFAULT 'MACHINE' COMMENT '审核来源：MACHINE机审/MANUAL人工审核',
    current_effective TINYINT NOT NULL DEFAULT 0 COMMENT '是否当前有效展示：0否/1是',
    provider_task_id BIGINT DEFAULT NULL COMMENT 'Provider 调用记录 ID',
    media_url VARCHAR(500) DEFAULT NULL COMMENT '图片、语音、材料等文件 URL',
    thumb_url VARCHAR(500) DEFAULT NULL COMMENT '图片缩略图 URL',
    duration INT DEFAULT NULL COMMENT '语音时长，单位秒',
    content_text VARCHAR(1000) DEFAULT NULL COMMENT '开放文本原文；语音不转文字',
    content_hash CHAR(64) DEFAULT NULL COMMENT '文本 SHA-256 哈希',
    real_name VARCHAR(50) DEFAULT NULL COMMENT '实名提交的真实姓名，业务明文入库',
    real_name_hash CHAR(64) DEFAULT NULL COMMENT '真实姓名 SHA-256 哈希',
    id_card VARCHAR(20) DEFAULT NULL COMMENT '身份证号，业务明文入库',
    id_card_hash CHAR(64) DEFAULT NULL COMMENT '身份证号 SHA-256 哈希',
    bound_phone VARCHAR(20) DEFAULT NULL COMMENT '实名提交时绑定手机号快照',
    education_method VARCHAR(50) DEFAULT NULL COMMENT '学历认证方式',
    school_name VARCHAR(100) DEFAULT NULL COMMENT '学校名称快照',
    education_level VARCHAR(50) DEFAULT NULL COMMENT '学历快照',
    submit_payload_json JSON DEFAULT NULL COMMENT '提交载荷快照',
    masked_payload_json JSON DEFAULT NULL COMMENT '脱敏载荷快照',
    material_json JSON DEFAULT NULL COMMENT '学历材料、图片组、问答等结构化补充',
    machine_signal_json JSON DEFAULT NULL COMMENT '机审标签、分值、命中原因',
    reject_reason VARCHAR(500) DEFAULT NULL COMMENT '驳回原因',
    expired_reason VARCHAR(500) DEFAULT NULL COMMENT '失效原因',
    submit_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户提交时间',
    audit_time DATETIME DEFAULT NULL COMMENT '审核完成时间',
    auditor_id BIGINT DEFAULT NULL COMMENT '人工审核管理员 ID',
    extra_json JSON DEFAULT NULL COMMENT '其他扩展数据',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT DEFAULT NULL COMMENT '创建人 ID',
    updated_by BIGINT DEFAULT NULL COMMENT '更新人 ID',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常/1删除',
    INDEX idx_audit_user_type_time (user_id, audit_type, submit_time),
    INDEX idx_audit_type_status (audit_type, status, deleted),
    INDEX idx_audit_source_status (audit_source, status, deleted),
    INDEX idx_audit_effective (user_id, audit_type, current_effective, deleted),
    INDEX idx_audit_object (audit_type, object_id, deleted),
    INDEX idx_audit_provider_task (provider_task_id),
    INDEX idx_audit_id_card_hash (id_card_hash, deleted),
    INDEX idx_audit_content_hash (audit_type, content_hash, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='App 用户统一审核记录表';

CREATE TABLE IF NOT EXISTS app_user_audit_history (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '自增主键',
    audit_record_id BIGINT NOT NULL COMMENT '审核记录 ID，关联 app_user_audit_record.id',
    user_id BIGINT NOT NULL COMMENT '用户 ID',
    audit_type VARCHAR(50) NOT NULL COMMENT '审核类型，同 app_user_audit_record.audit_type',
    from_status VARCHAR(20) DEFAULT NULL COMMENT '操作前状态',
    to_status VARCHAR(20) NOT NULL COMMENT '操作后状态',
    audit_source VARCHAR(20) NOT NULL COMMENT '审核来源：MACHINE机审/MANUAL人工审核',
    action VARCHAR(30) NOT NULL COMMENT '动作：SUBMIT/MACHINE_START/MACHINE_PASS/MACHINE_REJECT/MANUAL_APPROVE/MANUAL_REJECT/MANUAL_EXPIRE/SYSTEM_EXPIRE',
    reason VARCHAR(500) DEFAULT NULL COMMENT '驳回、失效、异常原因',
    operator_type VARCHAR(20) NOT NULL COMMENT '操作主体：USER/ADMIN/SYSTEM/PROVIDER',
    operator_id BIGINT DEFAULT NULL COMMENT '操作主体 ID',
    operator_name VARCHAR(80) DEFAULT NULL COMMENT '操作主体名称',
    provider_task_id BIGINT DEFAULT NULL COMMENT 'Provider 调用记录 ID',
    snapshot_json JSON DEFAULT NULL COMMENT '操作时关键快照',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by BIGINT DEFAULT NULL COMMENT '创建人 ID',
    updated_by BIGINT DEFAULT NULL COMMENT '更新人 ID',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常/1删除',
    INDEX idx_history_record_time (audit_record_id, create_time),
    INDEX idx_history_user_type_time (user_id, audit_type, create_time),
    INDEX idx_history_source_action (audit_source, action, create_time),
    INDEX idx_history_provider_task (provider_task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='App 用户审核历史表';
